yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:any_slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    ) 
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField("Название группы", max_length=200)
    slug = models.SlugField("Адрес", unique=True)
    description = models.TextField("Описание")

    class Meta:
        verbose_name_plural = "Группа"

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        "Текст поста",
        help_text="Введите текст поста"
    )
    group = models.ForeignKey(
        Group,
        related_name="groups_name",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор"
    )
    image = models.ImageField(
        "Картинка",
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name_plural = "Посты"
        ordering = ("-pub_date",)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField(
        "текст комментария",
        help_text="Введите текст комментария"
    )

    def __str__(self) -> str:
        return self.text[0:15]

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "Комментарии"


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор",
    )

    class Meta:
        verbose_name = "подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                name="unique_follower",
                fields=["user", "author"],
            ),
            models.CheckConstraint(
                name="not_self_follow",
                check=~models.Q(user=models.F("author")),
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

from yatube.settings import QUANTITY


@cache_page(20, key_prefix="index_page")
def index(request):
    template = "posts/index.html"
    title = "Последние обновления на сайте"
    posts = Post.objects.all()
    paginator = Paginator(posts, QUANTITY)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "title": title,
    }
    return render(request, template, context)


def group_posts(request, any_slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=any_slug)
    title = group
    posts = group.groups_name.all()
    paginator = Paginator(posts, QUANTITY)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "page_obj": page_obj,
        "title": title,
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    user = get_object_or_404(User, username=username)
    title = f"Профайл пользователя {username}"
    posts = Post.objects.filter(author=user)
    paginator = Paginator(posts, QUANTITY)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user
    ).exists()
    context = {
        "author": user,
        "page_obj": page_obj,
        "title": title,
        "following": following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = "posts/post_detail.html"
    post_item = get_object_or_404(Post, pk=post_id)
    title = f"Пост { post_item.text[0:30] }"
    form = CommentForm(request.POST or None)
    comment = post_item.comments.all()
    context = {
        "post_item": post_item,
        "title": title,
        "form": form,
        "comments": comment
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = "posts/create.html"
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", request.user.username)
    template = "posts/create.html"
    form = PostForm()
    context = {
        "form": form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post_item = get_object_or_404(Post, pk=post_id, author=request.user)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_item
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_item.id)
    form = PostForm(instance=post_item)
    template = "posts/create.html"
    context = {
        "post_item": post_item,
        "form": form,
        "is_edit": True
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    template = "posts/follow.html"
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, QUANTITY)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author
        )
        return redirect("posts:follow_index")
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    unfollow = get_object_or_404(User, username=username)
    follow = request.user.follower.filter(author=unfollow)
    if follow.exists():
        follow.delete()
    return redirect("posts:profile", username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% block title %} {{ title }}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data" action={% if is_edit %} "{% url 'posts:post_edit' post_id=post_item.id %}" {% else %} "{% url 'posts:post_create'%}" {% endif %}>
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>
                </label>
                {{ form.text }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка                      
                </label>
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Сообщество: {{ post.group }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text |linebreaks }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        <br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи сообщества</a>
        {% endif %}
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{ title }} </h1>
    <p> {{ title.description |linebreaks }} </p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Сообщество: {{ post.group }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text |linebreaks }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        <br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи сообщества</a>
        {% endif %} 
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}`
{% block content %}
  <div class="container py-5">
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Сообщество: {{ post.group }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text |linebreaks }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        <br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи сообщества</a>
        {% endif %}
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post_item.pub_date|date:"d E Y" }} 
          </li>
            <li class="list-group-item">
              {% if post_item.group %}
                Группа: {{ post_item.group }}
                <a href="{% url 'posts:group_list' post_item.group.slug %}">
                  все записи группы
                </a>
                {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post_item.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_item.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post_item.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {% thumbnail post_item.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {{ post_item.text |linebreaks }}        
        </p>
        {% if user == post_item.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post_item.id %}">
            редактировать запись
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post_item.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text|linebreaksbr }}
              </p>
            </div>
          </div>
        {% endfor %} 
      </article>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя
        {{ author.get_full_name }}
      </h1>
      <h3>Всего постов:
        {{ author.posts.count }}
      </h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    </div>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li> 
            Сообщество: 
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a>
            {% endif %}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text |linebreaks }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock %}